### ISSUE TITLE
The plugin does not import correctly

### ISSUE THREAD

**Issue by oredaze** [wojtryb/Shortcut-Composer#34]
**General info**
- Plugin version: 1.1.1, main and development
- Operating System: Gentoo
- Krita 5.1.5

**Bug description**
As seen in the screenshot the plugin does not import properly. No error popups or anything. Nothing works. I can assign shortcuts, but they do nothing. Also menu item "Tools > Scripts > Configure Shortcut Composer" does not exist.

![2023-02-12-133355_1920x1080_scrot](https://user-images.githubusercontent.com/51076873/218308775-bf9e7ec0-d1bf-4456-a6f6-599ecbd41329.png)

**Comment by wojtryb** [comment]
Hi, thank you for reporting.

Python is missing some libraries here. I believe you are not using an .appimage version of krita which is recommended way to use it on linux - only then developers can control what components are shipped with it.

If that's the case - please try it out. I assume currently your krita is using the system python instead of shipped one. Maybe this can be fixed by installing QtSql locally:

`sudo apt-get update -y`
`sudo apt-get install -y python-pyqt5.qtsql`

*Note that these are not tested - this is a first thing I googled - you may need to search further with it.

**Comment by oredaze** [comment]
Ah I see what is going on. This is a Gentoo specific problem.
I recompiled `dev-python/PyQt5` with `sql` use flag.
Thanks for the help.

I don't like using containers like appimage.
